name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Setup bats
      run: |
        sudo apt update
        sudo apt install -y bats
    - name: Run bats tests
      run: bats test/*.bats
